
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: development

test: &test
  <<: *default
  database: test

production:
  <<: *default
  database: production

cucumber:
  <<: *test